apiVersion: v1
kind: Secret
metadata:
  name: cap-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | quote }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.secrets.databaseEncryptionKey | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | quote }}
  MEDIA_SERVER_WEBHOOK_SECRET: {{ .Values.secrets.mediaServerWebhookSecret | quote }}
