#!/usr/bin/env bash
# Emit image-manifest.yaml with pinned digests when artifacts exist.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACTS="${ROOT}/supply-chain/artifacts"
REGISTRY="${REGISTRY_HOST:-localhost:5001}"
OUT="${1:-${ROOT}/dist/image-manifest.yaml}"

CAP_IMAGES=(
  "cap/cap-web:latest"
  "cap/media-server:latest"
  "cap/mysql:8.0"
  "cap/minio:latest"
  "cap/minio-mc:latest"
)

log() { echo "[image-manifest] $*"; }

digest_for() {
  local repo="$1"
  local tag="$2"
  local artifact="${ARTIFACTS}/$(echo "${repo}_${tag}" | tr '/:' '_').digest"
  if [[ -f "${artifact}" ]]; then
    tr -d '\n' < "${artifact}"
    return 0
  fi
  echo ""
}

mkdir -p "$(dirname "${OUT}")"
log "Writing ${OUT}"

{
  echo "# Generated by supply-chain/generate-image-manifest.sh"
  echo "registry: ${REGISTRY}"
  echo ""
  echo "cap:"
  for entry in "${CAP_IMAGES[@]}"; do
    repo="${entry%:*}"
    tag="${entry#*:}"
    digest="$(digest_for "${repo}" "${tag}")"
    echo "  - repository: ${repo}"
    echo "    tag: ${tag}"
    if [[ -n "${digest}" ]]; then
      echo "    digest: ${digest}"
      echo "    reference: ${digest}"
    else
      echo "    digest: null"
    fi
  done
  echo ""
  echo "addons:"
  echo "  # See supply-chain/dockerhub/tags.yaml for full addon relay list"
  echo "  note: Mirror addon images into your registry before install-addons"
} > "${OUT}"

log "Done"
